[package]
name = "taskwarrior-rofi"
version = "0.1.1"
edition = "2018"

[dependencies]
chrono = "0.4.19"
machine = "0.3.0"
open = "1.5.0"
rofi = "0.2.2"

[dependencies.task-hookrs]
git = "https://github.com/matthiasbeyer/task-hookrs.git"
rev = "bc70cae87ee3b48c720cf446c7f70374b78692e7"
